name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - 8.0
          - 7.4
          - 7.3
          - 7.2
          - 7.1
        env:
          - EXT_INSTALL=all
          - EXT_INSTALL=hrtime
          - EXT_INSTALL=uv
          - EXT_INSTALL=none
    steps:
      - uses: actions/checkout@v2
      - run: PHP_EXT_INSTALL=""
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "hrtime" ]]; then PHP_EXT_INSTALL = "$PHP_EXT_INSTALL hrtime"; fi
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "uv" ]]; then PHP_EXT_INSTALL = "$PHP_EXT_INSTALL uv-beta"; fi
      - run: export PHP_EXT_INSTALL
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "uv" ]]; then git clone https://github.com/libuv/libuv && cd libuv && git checkout tags/v1.28.0 && sh autogen.sh && ./configure && make && sudo make install && cd ..; fi
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: $PHP_EXT_INSTALL
          coverage: xdebug
      - run: composer install --no-interaction --ignore-platform-reqs
      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text
