name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} ${{ matrix.EXT_INSTALL }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - 8.0
          - 7.4
          - 7.3
          - 7.2
          - 7.1
        EXT_INSTALL: [all, hrtime, uv, none]
    steps:
      - uses: actions/checkout@v2
      - run: EXT_SETUP_PHP = ""
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "hrtime" ]]; then EXT_SETUP_PHP = "$EXT_SETUP_PHP hrtime"; fi
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "uv" ]]; then EXT_SETUP_PHP = "$EXT_SETUP_PHP uv-beta"; fi
      - run: export EXT_SETUP_PHP
      - run: if [[ "$EXT_INSTALL" = "all" || "$EXT_INSTALL" = "uv" ]]; then git clone https://github.com/libuv/libuv && cd libuv && git checkout tags/v1.28.0 && sh autogen.sh && ./configure && make && sudo make install && cd ..; fi
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: $EXT_SETUP_PHP
          coverage: xdebug
      - run: composer install --no-interaction --ignore-platform-reqs
        env:
          EXT_INSTALL: ${{ matrix.EXT_INSTALL }}
      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text
